### ISSUE TITLE
gulp-util deprecation

### ISSUE THREAD

**Issue by emilushi** [iShafayet/gulp-line-ending-corrector#3]
As you should know `gulp-util` is now depreciated but it is still a dependency.

    +-- gulp-line-ending-corrector@1.0.2
    | `-- gulp-util@3.0.8  deduped

Thanks!

**Comment by iShafayet** [comment]
Thank you. I'll get onto it.

**Comment by iShafayet** [comment]
@emilushi Issue should have been resolved in version 1.0.3. If issue persists, please reopen.
